site_name: 'Hermit'
site_description: 'Resettable Lazy delegates which automatically reset with a test lifecycle.'
site_author: '2020 Rick Busarow'
site_url: 'https://rbusarow.github.io/Hermit/'
remote_branch: gh-pages
docs_dir: '../docs'

# Repository
repo_name: 'Hermit'
repo_url: 'https://github.com/rbusarow/hermit'

# Copyright
copyright: 'Copyright &copy; 2020 Rick Busarow'

# Customization
extra:
  social:
    - type: github
      link: https://github.com/rbusarow/hermit
    - type: twitter
      link: https://twitter.com/rbusarow
    - type: linkedin
      link: https://linkedin.com/in/rick-busarow

nav:
  - 'Intro': index.md
  #  - 'Getting Started': getting-started.md
  - 'Modules':
      - 'Core': modules/hermit-core.md
      - 'Coroutines': modules/hermit-coroutines.md
      - 'JUnit4': modules/hermit-junit4.md
      - 'JUnit5': modules/hermit-junit5.md
      - 'MockK': modules/hermit-mockk.md
  #  - 'Change Log':
  - 'Change Log': CHANGELOG.md
  - 'API':
      - 'core': kdoc/hermit-core/index.md
      - 'coroutines': kdoc/hermit-coroutines/index.md
      - 'jUnit4': kdoc/hermit-junit4/index.md
      - 'jUnit5': kdoc/hermit-junit5/index.md
      - 'mockK': kdoc/hermit-mockk/index.md

theme:
  name: 'material'

  language: en
  feature:
    tabs: true
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: True
      use_pygments: True
      noclasses: True
  #      pygments_style: monokai
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true
