name: CI

on:
  push:
    branches:
      - dev
      - master
      - release/*
  pull_request:
    branches:
      - dev
      - master

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: all tests
        run: ./gradlew test

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#      There are currently no Android modules, so this doesn't actually resolve to a task (and therefore fails)
#      - name: lint
#        run: ./gradlew lint
